# Clase del 20 de agosto

## 1. Importar el dataset

In [10]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path.cwd() / "dataset.xlsx"

df = pd.read_excel(DATA_PATH)

df

,VehicleManufacturerName,TestVehDisplacement,RatedHorsepower,TestedTransmissionType,NoOfGears,DriveSystemDescription,EquivalentTestWeight,AxleRatio,TestFuelTypeDescription,TestCategory,AftertreatmentDevice,CO2Emissions,MPG
0,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,HWY,Three-way catalyst,287.000000,30.7
1,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Cold CO Premium (Tier 2),FTP,Three-way catalyst,467.000000,18.8
2,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,FTP,Three-way catalyst,389.000000,22.7
3,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,SC03,Three-way catalyst,475.000000,18.6
4,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,US06,Three-way catalyst,411.000000,21.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,Volkswagen,3.596,280,Automatic,6,"2-Wheel Drive, Front",5500,4.30,Tier 2 Cert Gasoline,FTP,Three-way catalyst,542.029517,16.4
1064,Volkswagen,3.596,280,Automatic,6,"2-Wheel Drive, Front",5500,4.30,Tier 2 Cert Gasoline,HWY,Three-way catalyst,351.227875,25.3
1065,Volvo,2.953,281,Semi-Automatic,6,"2-Wheel Drive, Front",4500,3.75,CARB Phase II Gasoline,FTP,Three-way catalyst,451.300000,19.4
1066,Volvo,2.953,281,Semi-Automatic,6,"2-Wheel Drive, Front",4500,3.75,CARB Phase II Gasoline,HWY,Three-way catalyst,288.000000,30.4
1067,Volvo,2.953,281,Semi-Automatic,6,"2-Wheel Drive, Front",4500,3.75,CARB Phase II Gasoline,SC03,Three-way catalyst,509.000000,17.2

## 2. Revisar los datos faltantes

In [11]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isna().sum() / len(df) * 100).round(2)
})

missing_summary

                         Missing Count  Missing Percentage
VehicleManufacturerName              0                0.00
TestVehDisplacement                  0                0.00
RatedHorsepower                      0                0.00
TestedTransmissionType               0                0.00
NoOfGears                            0                0.00
DriveSystemDescription               0                0.00
EquivalentTestWeight                 0                0.00
AxleRatio                            0                0.00
TestFuelTypeDescription              0                0.00
TestCategory                         0                0.00
AftertreatmentDevice               235               22.00
CO2Emissions                       188               17.60
MPG                                  1                0.09

**Data imputation** es una técnica muy común que consiste en el proceso de reemplazar valores faltantes o nulos en un conjunto de datos con sustitutos estimados o plausibles (media, moda, mediana, etc.). Es importante saber cuando utilizarla porque puede generar **data leakage** porque al hacer uso de información artificial durante el entrenamiento del modelo aumenta la posibilidad de que las predicciones que haga no sean útiles, ya que se hace dependiente a información que no estará disponible al momento de hacer predicciones reales.


## 3. A continuación se hace una eliminación de filas para evitar afectar el modelo con valores faltantes

Pasamos de tener 1068 filas a 744 columnas

In [14]:
df1 = df.dropna(subset=["CO2Emissions", "MPG", "AftertreatmentDevice"]).copy()

df1

,VehicleManufacturerName,TestVehDisplacement,RatedHorsepower,TestedTransmissionType,NoOfGears,DriveSystemDescription,EquivalentTestWeight,AxleRatio,TestFuelTypeDescription,TestCategory,AftertreatmentDevice,CO2Emissions,MPG
0,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,HWY,Three-way catalyst,287.000000,30.7
1,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Cold CO Premium (Tier 2),FTP,Three-way catalyst,467.000000,18.8
2,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,FTP,Three-way catalyst,389.000000,22.7
3,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,SC03,Three-way catalyst,475.000000,18.6
4,Audi,3.179,270,Automatic,6,"2-Wheel Drive, Front",4500,4.22,Tier 2 Cert Gasoline,US06,Three-way catalyst,411.000000,21.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,Volkswagen,3.596,280,Automatic,6,"2-Wheel Drive, Front",5500,4.30,Tier 2 Cert Gasoline,FTP,Three-way catalyst,542.029517,16.4
1064,Volkswagen,3.596,280,Automatic,6,"2-Wheel Drive, Front",5500,4.30,Tier 2 Cert Gasoline,HWY,Three-way catalyst,351.227875,25.3
1065,Volvo,2.953,281,Semi-Automatic,6,"2-Wheel Drive, Front",4500,3.75,CARB Phase II Gasoline,FTP,Three-way catalyst,451.300000,19.4
1066,Volvo,2.953,281,Semi-Automatic,6,"2-Wheel Drive, Front",4500,3.75,CARB Phase II Gasoline,HWY,Three-way catalyst,288.000000,30.4
1067,Volvo,2.953,281,Semi-Automatic,6,"2-Wheel Drive, Front",4500,3.75,CARB Phase II Gasoline,SC03,Three-way catalyst,509.000000,17.2

In [15]:
missing_summary = pd.DataFrame({
    "Missing Count": df1.isna().sum(),
    "Missing Percentage": (df1.isna().sum() / len(df1) * 100).round(2)
})

missing_summary

                         Missing Count  Missing Percentage
VehicleManufacturerName              0                 0.0
TestVehDisplacement                  0                 0.0
RatedHorsepower                      0                 0.0
TestedTransmissionType               0                 0.0
NoOfGears                            0                 0.0
DriveSystemDescription               0                 0.0
EquivalentTestWeight                 0                 0.0
AxleRatio                            0                 0.0
TestFuelTypeDescription              0                 0.0
TestCategory                         0                 0.0
AftertreatmentDevice                 0                 0.0
CO2Emissions                         0                 0.0
MPG                                  0                 0.0

## 4. Cambiar las variables categoricas a representaciones númericas

Los números asignados no representan una jerarquía, si no que se usan para diferencias los diferentes valores de cada variable para poder ser analizados más fácilmente por el modelo.

In [17]:
from sklearn.preprocessing import LabelEncoder
from IPython.display import display
import pandas as pd

df_encoded = df1.copy()

categorical_columns = ["VehicleManufacturerName", "TestedTransmissionType", "DriveSystemDescription", "TestCategory", "TestFuelTypeDescription", "AftertreatmentDevice"]

label_encoders = {}
mapping_tables = {}

for col in categorical_columns:
    le = LabelEncoder()
    # Replace original with encoded values
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
    # Save encoder
    label_encoders[col] = pd.DataFrame({
        "Category": le.classes_,
        "Encoded Value": le.transform(le.classes_)
    })

# Display mappigs
for col, mapping in mapping_tables.items():
    print(f"\nMapping for {col}:")
    display(mapping)

df_encoded

,VehicleManufacturerName,TestVehDisplacement,RatedHorsepower,TestedTransmissionType,NoOfGears,DriveSystemDescription,EquivalentTestWeight,AxleRatio,TestFuelTypeDescription,TestCategory,AftertreatmentDevice,CO2Emissions,MPG
0,0,3.179,270,0,6,0,4500,4.22,5,1,4,287.000000,30.7
1,0,3.179,270,0,6,0,4500,4.22,1,0,4,467.000000,18.8
2,0,3.179,270,0,6,0,4500,4.22,5,0,4,389.000000,22.7
3,0,3.179,270,0,6,0,4500,4.22,5,2,4,475.000000,18.6
4,0,3.179,270,0,6,0,4500,4.22,5,3,4,411.000000,21.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,17,3.596,280,0,6,0,5500,4.30,5,0,4,542.029517,16.4
1064,17,3.596,280,0,6,0,5500,4.30,5,1,4,351.227875,25.3
1065,18,2.953,281,4,6,0,4500,3.75,0,0,4,451.300000,19.4
1066,18,2.953,281,4,6,0,4500,3.75,0,1,4,288.000000,30.4
1067,18,2.953,281,4,6,0,4500,3.75,0,2,4,509.000000,17.2

## 5. 
Single Layer Perceptron es un tipo de simulación neuronal

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.neural_network import MLPRegressor 
from sklearn.metrics import mean_squared_error 
from sklearn.exceptions import ConvergenceWarning 
import warnings

warnings.filterwarnings ("ignore", category=ConvergenceWarning)

feature_cols = [c for c in df_encoded. columns if c not in ["CO2Emissions", "MPG"]]

data_model = df_encoded[feature_cols + ["CO2Emissions"]].dropna()

X = data_model[feature_cols].to_numpy()
y = data_model["CO2Emissions"].to_numpy().reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train = scaler_X.fit_transform(X_train)
X_test = scaler_X.transform(X_test)

y_train_scaled = scaler_y.fit_transform(y_train).ravel()
y_test_scaled = scaler_y.transform(y_test).ravel()

mlp = MLPRegressor(
    hidden_layer_sizes=(64, 32), activation="relu", solver="adam", learning_rate_init=0.001, max_iter=1, warm_start=True,
    random_state=42, shuffle=True
)

epochs = 300 # Iteraciones en el proceso de testing interno para buscar la mejora

train_errors =